application: offeringsignup
version: 1
runtime: go
api_version: go1

handlers:

- url: /
  static_files: static/index.html
  upload: /static/index.html

- url: /events
  static_files: static/events.html
  upload: /static/events.html

- url: /event
  static_files: static/event.html
  upload: /static/event.html


- url: /static/
  static_dir: static

- url: /.*
  script: _go_app

skip_files:

- static/src/*
- node_modules/.*
